### PR TITLE
Json formatting

### PR DESCRIPTION
**Pull request by janakagamini**
All GET results that have 1 or more rows will be wrapped in a JSON array.

### CODE REVIEW

**Comment by jexp** [comment]
We should also update the docs in the readme. Just add the commit and push again.
I wonder if we should have a different endpoint (or an http header) for single row results which always return objects?
And perhaps also support ?limit= and ?skip= query params?

If you could merge your commit, that would be great.

On the commandline `git rebase -i HEAD~4 `
Choose `pick` for the first commit and `squash` for the others.

Then git merges all of them together.

**Comment by jexp** [comment]
Thanks a lot @janakagamini

**Comment by janakagamini** [comment]
Hello @jexp 

I updated the docs, also pretty formatted all the JSON in the docs for readability.

Re - single row results: My personal opinion is that a single consistent method for delivering all results is best (like the neo4j cypher transactional endpoint). Users can easily retrieve an object from a list whether it be a list with one object or many objects. This also brings another point to mind regarding a query that returns no results. Should it be `204 Not Content` or `200 OK` with body as `[]`.

But then again, cypher-rs is about giving the developer the flexibility to design his own endpoints, right? In that case I guess some form of http header setting will be good.

I agree `skip`, `limit` and perhaps `order by` should be supported as query parameters. That would be really neat!

By the way I did:

    prompt>git rebase -i HEAD~5
    [detached HEAD 76915cf] Fixing JSON format
     Author: Janaka <myemail@somedomain.com>
     4 files changed, 180 insertions(+), 37 deletions(-)
    Successfully rebased and updated refs/heads/json_formatting.

I'm not sure if I say any changes on GitHub though. Apologies I'm still not very familiar with this.

**Comment by jexp** [comment]
You have to push to your branch `git push -f origin HEAD:json_formatting `

or if you branch is called differently:

`git push -f janakagamini HEAD:json_formatting `

**Comment by janakagamini** [comment]
Done (I think?). Thanks for your patience.

**Comment by jexp** [comment]
Thank you !! 
Something is still off, you should have only one commit left in your branch. I.e. "pick" the first and "squash" the 6.

**Comment by jexp** [comment]
I can also do it locally if you want me to.

**Comment by janakagamini** [comment]
@jexp: Perhaps you should do it. I'd rather not pollute this thread with me trying to learn git.

Thanks!

**Comment by jexp** [comment]
Merged Manually

**Pull request closed without merging**
